site_name: LouieAI Client
site_description: Documentation for the LouieAI Python client library.
site_url: https://louie-py.readthedocs.io
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Authentication: getting-started/authentication.md
    - Quick Start: getting-started/quick-start.md
    - Example Notebooks:
      - Getting Started: getting-started/notebooks/01-getting-started.ipynb
      - Data Science Workflow: getting-started/notebooks/02-data-science-workflow.ipynb
      - Fraud Investigation: getting-started/notebooks/03-fraud-investigation.ipynb
      - Error Handling: getting-started/notebooks/04-error-handling.ipynb
  - User Guides:
    - Examples: guides/examples.md
    - Query Patterns: guides/query-patterns.md
    - Authentication Guide: guides/authentication.md
  - API Reference:
    - Overview: api/index.md
    - Notebook API: api/notebook.md
    - LouieClient: api/client.md
    - Response Types: api/response-types.md
  - Developer:
    - Architecture: developer/architecture.md
    - Development: developer/development.md
    - Testing: developer/testing.md
    - Publishing: developer/publishing.md
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
  logo: assets/louie-logo.png
  favicon: assets/louie-logo.png
docs_dir: docs
repo_url: https://github.com/graphistry/louie-py
repo_name: graphistry/louie-py
plugins:
  - search
  - mkdocs-jupyter:
      execute: false  # Don't execute notebooks during build
      include_source: false  # Don't show notebook source JSON
      ignore_h1_titles: true  # Use the nav title instead of notebook H1
      allow_errors: true  # Continue if notebook has errors
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            members_order: source