name: CI
on:
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv pip install -e ".[dev]"
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (ruff)
        run: ruff format --check .
      - name: Type Check (mypy)
        run: mypy .
      - name: Run Tests
        run: pytest -q --cov=louieai --cov-report=xml --cov-report=term --cov-fail-under=85